//! AUDESYS type system tests — generated from openspec/specs/
//! Source: hal-type-system-spec.md
//! Phase: P0
//!
//! Each #[test] maps to a spec ID.
//! Generated by /test-harness generate — 2026-07-15
//!
//! # Decision references
//! - D33: direct TDD
//! - D48: SDD spec generation
//! - D50: test-harness auto-generation

use audesys_hal_core::types::{HalError, HalPinType};
use audesys_hal_core::{HalValue, decode_halvalue, encode_halvalue};

// ── Float comparison helpers ──

/// Roundtrip f32 values and compare via to_bits() (NaN-safe).
fn rt_f32(v: HalValue) {
    let encoded = encode_halvalue(&v);
    let decoded = decode_halvalue(&encoded).expect("decode f32 failed");
    match (&v, &decoded) {
        (HalValue::F32(a), HalValue::F32(b)) => {
            assert_eq!(a.to_bits(), b.to_bits(), "f32 roundtrip bit mismatch");
        }
        _ => panic!("expected F32 roundtrip, got {:?} → {:?}", v, decoded),
    }
}

/// Roundtrip f64 values and compare via to_bits() (NaN-safe).
fn rt_f64(v: HalValue) {
    let encoded = encode_halvalue(&v);
    let decoded = decode_halvalue(&encoded).expect("decode f64 failed");
    match (&v, &decoded) {
        (HalValue::F64(a), HalValue::F64(b)) => {
            assert_eq!(a.to_bits(), b.to_bits(), "f64 roundtrip bit mismatch");
        }
        _ => panic!("expected F64 roundtrip, got {:?} → {:?}", v, decoded),
    }
}

/// Roundtrip a non-float HalValue via PartialEq.
fn rt(v: HalValue) {
    let encoded = encode_halvalue(&v);
    let decoded = decode_halvalue(&encoded).expect("decode failed");
    assert_eq!(v, decoded, "roundtrip mismatch for {:?}", v);
}

// ═══════════════════════════════════════════════════════════════
// P0 tests — 23 type system validations (Phase 1 M0.3)
// ═══════════════════════════════════════════════════════════════

#[test]
fn test_type_01_bool_roundtrip() {
    // S-TYPE-001: Bool 序列化往返
    rt(HalValue::Bool(true));
    rt(HalValue::Bool(false));
}

#[test]
fn test_type_02_s8_roundtrip() {
    // S-TYPE-002: S8 序列化往返 — key boundary values
    rt(HalValue::S8(-128));
    rt(HalValue::S8(-1));
    rt(HalValue::S8(0));
    rt(HalValue::S8(1));
    rt(HalValue::S8(127));
}

#[test]
fn test_type_03_u8_roundtrip() {
    // S-TYPE-003: U8 序列化往返 — key boundary values
    rt(HalValue::U8(0));
    rt(HalValue::U8(1));
    rt(HalValue::U8(127));
    rt(HalValue::U8(254));
    rt(HalValue::U8(255));
}

#[test]
fn test_type_04_s16_roundtrip() {
    // S-TYPE-004: S16 序列化往返
    rt(HalValue::S16(-32768));
    rt(HalValue::S16(-1));
    rt(HalValue::S16(0));
    rt(HalValue::S16(1));
    rt(HalValue::S16(32767));
}

#[test]
fn test_type_05_u16_roundtrip() {
    // S-TYPE-005: U16 序列化往返
    rt(HalValue::U16(0));
    rt(HalValue::U16(1));
    rt(HalValue::U16(32768));
    rt(HalValue::U16(65534));
    rt(HalValue::U16(65535));
}

#[test]
fn test_type_06_s32_roundtrip() {
    // S-TYPE-006: S32 序列化往返 — min, -1, 0, 1, max
    rt(HalValue::S32(i32::MIN));
    rt(HalValue::S32(-1));
    rt(HalValue::S32(0));
    rt(HalValue::S32(1));
    rt(HalValue::S32(i32::MAX));
}

#[test]
fn test_type_07_u32_roundtrip() {
    // S-TYPE-007: U32 序列化往返 — 0, 1, max
    rt(HalValue::U32(0));
    rt(HalValue::U32(1));
    rt(HalValue::U32(u32::MAX));
}

#[test]
fn test_type_08_s64_roundtrip() {
    // S-TYPE-008: S64 序列化往返 — min, -1, 0, 1, max
    rt(HalValue::S64(i64::MIN));
    rt(HalValue::S64(-1));
    rt(HalValue::S64(0));
    rt(HalValue::S64(1));
    rt(HalValue::S64(i64::MAX));
}

#[test]
fn test_type_09_u64_roundtrip() {
    // S-TYPE-009: U64 序列化往返 — 0, 1, max
    rt(HalValue::U64(0));
    rt(HalValue::U64(1));
    rt(HalValue::U64(u64::MAX));
}

#[test]
fn test_type_10_f32_roundtrip() {
    // S-TYPE-010: F32 序列化往返 — use to_bits() for NaN safety
    rt_f32(HalValue::F32(0.0));
    rt_f32(HalValue::F32(-1.0));
    rt_f32(HalValue::F32(std::f32::consts::PI));
    rt_f32(HalValue::F32(f32::MIN));
    rt_f32(HalValue::F32(f32::MAX));
}

#[test]
fn test_type_11_f64_roundtrip() {
    // S-TYPE-011: F64 序列化往返 — use to_bits() for NaN safety
    rt_f64(HalValue::F64(0.0));
    rt_f64(HalValue::F64(-1.0));
    rt_f64(HalValue::F64(std::f64::consts::PI));
    rt_f64(HalValue::F64(f64::MIN));
    rt_f64(HalValue::F64(f64::MAX));
}

#[test]
fn test_type_12_blob_roundtrip() {
    // S-TYPE-012: Blob roundtrip — empty, small, 256-byte
    rt(HalValue::Blob(vec![]));
    rt(HalValue::Blob(vec![0, 1, 2]));
    rt(HalValue::Blob(vec![255; 256]));
}

#[test]
fn test_type_13_string_roundtrip() {
    // S-TYPE-013: String roundtrip
    rt(HalValue::String("".into()));
    rt(HalValue::String("hello".into()));
    rt(HalValue::String("中文".into()));
    // ponytail: max_len_string — 1KB ASCII
    let max_len = "a".repeat(1024);
    rt(HalValue::String(max_len));
}

#[test]
fn test_type_14_array_roundtrip() {
    // S-TYPE-014: Array<T> roundtrip — S32 elements
    // Arrange: 4-byte LE encoding of [0] as S32 = [0,0,0,0]
    let v = HalValue::Array { element_type: HalPinType::S32, data: vec![0, 0, 0, 0] };
    rt(v);
}

#[test]
fn test_type_15_blob_length_mismatch() {
    // S-TYPE-015: Blob length validation — corrupt length byte
    // Arrange: encode valid blob
    let v = HalValue::Blob(vec![1, 2, 3, 4]);
    let mut encoded = encode_halvalue(&v);
    // Corrupt the 4-byte length field (bytes 1-4 after type tag 0)
    let fake_len: u32 = 999;
    encoded[1..5].copy_from_slice(&fake_len.to_le_bytes());
    // Act
    let result = decode_halvalue(&encoded);
    // Assert
    assert!(
        matches!(result, Err(HalError::InvalidBlobLength { .. })),
        "expected InvalidBlobLength, got {:?}",
        result
    );
}

#[test]
fn test_type_16_array_type_mismatch() {
    // S-TYPE-016: Array element_type validation — corrupt element_type byte
    // Arrange: encode valid Array, then corrupt element_type tag (byte 1, after TAG_ARRAY)
    let v = HalValue::Array { element_type: HalPinType::S32, data: vec![0, 0, 0, 0] };
    let mut encoded = encode_halvalue(&v);
    encoded[1] = 0xFF; // invalid element_type tag
    // Act
    let result = decode_halvalue(&encoded);
    // Assert
    assert!(
        matches!(result, Err(HalError::TypeMismatch { .. })),
        "expected TypeMismatch, got {:?}",
        result
    );
}

#[test]
fn test_type_18_unknown_type_id() {
    // S-TYPE-018: Unknown type tag rejection — 0xFF
    // Arrange: manually construct buffer with type tag 0xFF
    let buf = [0xFF, 0x00];
    // Act
    let result = decode_halvalue(&buf);
    // Assert
    assert!(
        matches!(result, Err(HalError::UnknownHalType { type_id: 0xFF })),
        "expected UnknownHalType, got {:?}",
        result
    );
}

#[test]
fn test_type_19_nesting_limit() {
    // S-TYPE-019: Array of Blob — decode handles non-scalar element_type
    // Arrange: encode Array { element_type: Blob, data: single encoded empty blob }
    let inner_blob = encode_halvalue(&HalValue::Blob(vec![]));
    let v = HalValue::Array { element_type: HalPinType::Blob, data: inner_blob };
    // Act
    let encoded = encode_halvalue(&v);
    let decoded = decode_halvalue(&encoded).expect("decode Array<Blob> failed");
    // Assert
    match decoded {
        HalValue::Array { element_type, .. } => {
            assert_eq!(element_type, HalPinType::Blob);
        }
        _ => panic!("expected Array, got {:?}", decoded),
    }
}

#[test]
fn test_type_20_blob_empty() {
    // S-TYPE-020: Blob with declared length 0, actual 0 bytes
    rt(HalValue::Blob(vec![]));
}

#[test]
fn test_type_21_blob_max() {
    // S-TYPE-021: Blob with declared max size — 65535 bytes
    // ponytail: one large alloc, not production-size
    let data = vec![0u8; 65535];
    rt(HalValue::Blob(data));
}

#[test]
fn test_type_22_string_empty() {
    // S-TYPE-022: Empty string roundtrip
    rt(HalValue::String("".into()));
}

#[test]
fn test_type_23_string_unicode() {
    // S-TYPE-023: Unicode string roundtrip
    rt(HalValue::String("Hello 世界 🌍".into()));
}

#[test]
fn test_type_28_nan_bitwise() {
    // S-TYPE-028: NaN bitwise survival — encode f32::NAN, compare with to_bits()
    rt_f32(HalValue::F32(f32::NAN));
}

#[test]
fn test_type_30_pin_type_identity() {
    // S-TYPE-030: For each variant, pin_type() returns correct HalPinType
    assert_eq!(HalValue::Bool(true).pin_type(), HalPinType::Bool);
    assert_eq!(HalValue::Bool(false).pin_type(), HalPinType::Bool);
    assert_eq!(HalValue::S8(0).pin_type(), HalPinType::S8);
    assert_eq!(HalValue::U8(0).pin_type(), HalPinType::U8);
    assert_eq!(HalValue::S16(0).pin_type(), HalPinType::S16);
    assert_eq!(HalValue::U16(0).pin_type(), HalPinType::U16);
    assert_eq!(HalValue::S32(0).pin_type(), HalPinType::S32);
    assert_eq!(HalValue::U32(0).pin_type(), HalPinType::U32);
    assert_eq!(HalValue::S64(0).pin_type(), HalPinType::S64);
    assert_eq!(HalValue::U64(0).pin_type(), HalPinType::U64);
    assert_eq!(HalValue::F32(0.0).pin_type(), HalPinType::F32);
    assert_eq!(HalValue::F64(0.0).pin_type(), HalPinType::F64);
    assert_eq!(HalValue::Blob(vec![]).pin_type(), HalPinType::Blob);
    assert_eq!(HalValue::String("".into()).pin_type(), HalPinType::String);
    assert_eq!(
        HalValue::Array { element_type: HalPinType::S32, data: vec![] }.pin_type(),
        HalPinType::S32
    );
}

// ═══════════════════════════════════════════════════════════════
// P1 tests — Phase 1 M0.5 implementations
// ═══════════════════════════════════════════════════════════════

#[test]
fn test_type_17_zero_value() {
    // S-TYPE-017: String UTF-8 validation — invalid UTF-8 is rejected, valid passes
    // Arrange: encode a valid string, then corrupt bytes to invalid UTF-8
    let v = HalValue::String("hello".into());
    let mut encoded = encode_halvalue(&v);
    // Replace byte 5 ('h', 0x68) with invalid lone 0xFF
    encoded[5] = 0xFF;
    // Act
    let result = decode_halvalue(&encoded);
    // Assert: 0xFF is not valid UTF-8
    assert!(
        matches!(result, Err(HalError::InvalidUtf8)),
        "expected InvalidUtf8 for 0xFF byte, got {:?}",
        result
    );
    // Also verify: truncated multi-byte UTF-8 sequence rejected
    let v2 = HalValue::String("é".into()); // 0xC3 0xA9 (2-byte sequence)
    let mut encoded2 = encode_halvalue(&v2);
    // Truncate to keep only the leading byte of the 2-byte sequence
    encoded2.truncate(6); // tag(1) + len(4) + 1 partial byte
    let new_len: u32 = 1;
    encoded2[1..5].copy_from_slice(&new_len.to_le_bytes());
    let result2 = decode_halvalue(&encoded2);
    assert!(
        matches!(result2, Err(HalError::InvalidUtf8)),
        "expected InvalidUtf8 for truncated UTF-8, got {:?}",
        result2
    );
    // Verify valid UTF-8 with multi-byte chars passes cleanly
    rt(HalValue::String("valid UTF-8 ✓ 中文 🎯".into()));
}

#[test]
fn test_type_24_numeric_edges() {
    // S-TYPE-024: Bool narrowing — any non-zero byte maps to true
    // Arrange: encode Bool(false), then mutate payload byte
    let v = HalValue::Bool(false);
    let mut encoded = encode_halvalue(&v);
    // Act & Assert: various non-zero bytes all decode as true
    for &byte in &[0x01u8, 0xFF, 0x42, 0x80] {
        encoded[1] = byte;
        let decoded = decode_halvalue(&encoded).expect("decode failed");
        assert_eq!(decoded, HalValue::Bool(true), "byte 0x{:02X} should be narrowed to true", byte);
    }
    // Zero byte → false
    encoded[1] = 0x00;
    let decoded = decode_halvalue(&encoded).expect("decode failed");
    assert_eq!(decoded, HalValue::Bool(false));
}

#[test]
fn test_type_25_container_large() {
    // S-TYPE-025: Blob zero-length pointer — 0-byte blob encodes/decodes cleanly
    // Arrange: empty blob
    let v = HalValue::Blob(vec![]);
    // Act: encode and verify layout
    let encoded = encode_halvalue(&v);
    // Assert: empty blob = tag(1) + 4-byte zero-length = exactly 5 bytes
    assert_eq!(encoded.len(), 5, "empty blob should be exactly 5 bytes (tag + 4-byte length)");
    let decoded = decode_halvalue(&encoded).expect("decode empty blob failed");
    assert_eq!(decoded, HalValue::Blob(vec![]));
    // Also verify single-byte and moderate-sized blobs
    rt(HalValue::Blob(vec![42]));
    rt(HalValue::Blob(vec![0xCC; 4096]));
}

#[test]
fn test_type_26_type_mapping() {
    // S-TYPE-026: Array large boundary — verify large arrays roundtrip correctly
    // Arrange: 10K-element S8 array (ponytail: not production-scale)
    let data = vec![0xABu8; 10000];
    let v = HalValue::Array { element_type: HalPinType::S8, data };
    // Act
    let encoded = encode_halvalue(&v);
    let decoded = decode_halvalue(&encoded).expect("decode large Array failed");
    // Assert: element_type and data preserved
    match &decoded {
        HalValue::Array { element_type, data } => {
            assert_eq!(*element_type, HalPinType::S8);
            assert_eq!(data.len(), 10000);
            assert_eq!(data[0], 0xAB);
            assert_eq!(data[9999], 0xAB);
        }
        _ => panic!("expected Array<S8>, got {:?}", decoded),
    }
    assert_eq!(v, decoded, "large Array roundtrip mismatch");
}

#[test]
fn test_type_27_stress_roundtrip() {
    // S-TYPE-027: String length boundaries — empty, short, null-embedded, long, unicode
    // Empty string
    rt(HalValue::String("".into()));
    // Single ASCII character
    rt(HalValue::String("A".into()));
    // String with embedded null characters (should survive roundtrip)
    rt(HalValue::String("before\0after".into()));
    // Long string — 4KB of repeated 'x'
    let long = "x".repeat(4096);
    rt(HalValue::String(long));
    // 4-byte UTF-8 emoji (boundary: max bytes per code point)
    rt(HalValue::String("😀".into()));
}

#[test]
fn test_type_29_container_overlap() {
    // S-TYPE-029: Scalar retagging safety — same bit-pattern, different type tags
    // Arrange: U32::MAX and S32(-1) have identical 4-byte LE payload [FF,FF,FF,FF]
    let u32_val = HalValue::U32(u32::MAX);
    let s32_val = HalValue::S32(-1);
    // Act: encode both
    let u32_enc = encode_halvalue(&u32_val);
    let s32_enc = encode_halvalue(&s32_val);
    // Assert: different type tags (6 vs 5), identical payload bytes
    assert_eq!(u32_enc[0], 6, "U32 tag should be 6");
    assert_eq!(s32_enc[0], 5, "S32 tag should be 5");
    assert_eq!(&u32_enc[1..], &s32_enc[1..], "payload bytes should be identical");
    // Roundtrip preserves correct type (not cross-interpreted)
    assert_eq!(decode_halvalue(&u32_enc).unwrap(), u32_val);
    assert_eq!(decode_halvalue(&s32_enc).unwrap(), s32_val);
    // Same pattern for U64/S64: U64::MAX and S64(-1) both = [FF;8]
    let u64_val = HalValue::U64(u64::MAX);
    let s64_val = HalValue::S64(-1);
    let u64_enc = encode_halvalue(&u64_val);
    let s64_enc = encode_halvalue(&s64_val);
    assert_eq!(u64_enc[0], 8, "U64 tag should be 8");
    assert_eq!(s64_enc[0], 7, "S64 tag should be 7");
    assert_eq!(&u64_enc[1..], &s64_enc[1..], "payload bytes should be identical");
    assert_eq!(decode_halvalue(&u64_enc).unwrap(), u64_val);
    assert_eq!(decode_halvalue(&s64_enc).unwrap(), s64_val);
}
