//! AUDESYS type system tests — generated from openspec/specs/
//! Source: hal-type-system-spec.md
//! Phase: P0
//!
//! Each #[test] maps to a spec ID.
//! Generated by /test-harness generate — 2026-07-15
//!
//! # Decision references
//! - D33: direct TDD
//! - D48: SDD spec generation
//! - D50: test-harness auto-generation

use audesys_hal_core::types::{HalError, HalPinType};
use audesys_hal_core::{HalValue, decode_halvalue, encode_halvalue};

// ── Float comparison helpers ──

/// Roundtrip f32 values and compare via to_bits() (NaN-safe).
fn rt_f32(v: HalValue) {
    let encoded = encode_halvalue(&v);
    let decoded = decode_halvalue(&encoded).expect("decode f32 failed");
    match (&v, &decoded) {
        (HalValue::F32(a), HalValue::F32(b)) => {
            assert_eq!(a.to_bits(), b.to_bits(), "f32 roundtrip bit mismatch");
        }
        _ => panic!("expected F32 roundtrip, got {:?} → {:?}", v, decoded),
    }
}

/// Roundtrip f64 values and compare via to_bits() (NaN-safe).
fn rt_f64(v: HalValue) {
    let encoded = encode_halvalue(&v);
    let decoded = decode_halvalue(&encoded).expect("decode f64 failed");
    match (&v, &decoded) {
        (HalValue::F64(a), HalValue::F64(b)) => {
            assert_eq!(a.to_bits(), b.to_bits(), "f64 roundtrip bit mismatch");
        }
        _ => panic!("expected F64 roundtrip, got {:?} → {:?}", v, decoded),
    }
}

/// Roundtrip a non-float HalValue via PartialEq.
fn rt(v: HalValue) {
    let encoded = encode_halvalue(&v);
    let decoded = decode_halvalue(&encoded).expect("decode failed");
    assert_eq!(v, decoded, "roundtrip mismatch for {:?}", v);
}

// ═══════════════════════════════════════════════════════════════
// P0 tests — 23 type system validations (Phase 1 M0.3)
// ═══════════════════════════════════════════════════════════════

#[test]
fn test_type_01_bool_roundtrip() {
    // S-TYPE-001: Bool 序列化往返
    rt(HalValue::Bool(true));
    rt(HalValue::Bool(false));
}

#[test]
fn test_type_02_s8_roundtrip() {
    // S-TYPE-002: S8 序列化往返 — key boundary values
    rt(HalValue::S8(-128));
    rt(HalValue::S8(-1));
    rt(HalValue::S8(0));
    rt(HalValue::S8(1));
    rt(HalValue::S8(127));
}

#[test]
fn test_type_03_u8_roundtrip() {
    // S-TYPE-003: U8 序列化往返 — key boundary values
    rt(HalValue::U8(0));
    rt(HalValue::U8(1));
    rt(HalValue::U8(127));
    rt(HalValue::U8(254));
    rt(HalValue::U8(255));
}

#[test]
fn test_type_04_s16_roundtrip() {
    // S-TYPE-004: S16 序列化往返
    rt(HalValue::S16(-32768));
    rt(HalValue::S16(-1));
    rt(HalValue::S16(0));
    rt(HalValue::S16(1));
    rt(HalValue::S16(32767));
}

#[test]
fn test_type_05_u16_roundtrip() {
    // S-TYPE-005: U16 序列化往返
    rt(HalValue::U16(0));
    rt(HalValue::U16(1));
    rt(HalValue::U16(32768));
    rt(HalValue::U16(65534));
    rt(HalValue::U16(65535));
}

#[test]
fn test_type_06_s32_roundtrip() {
    // S-TYPE-006: S32 序列化往返 — min, -1, 0, 1, max
    rt(HalValue::S32(i32::MIN));
    rt(HalValue::S32(-1));
    rt(HalValue::S32(0));
    rt(HalValue::S32(1));
    rt(HalValue::S32(i32::MAX));
}

#[test]
fn test_type_07_u32_roundtrip() {
    // S-TYPE-007: U32 序列化往返 — 0, 1, max
    rt(HalValue::U32(0));
    rt(HalValue::U32(1));
    rt(HalValue::U32(u32::MAX));
}

#[test]
fn test_type_08_s64_roundtrip() {
    // S-TYPE-008: S64 序列化往返 — min, -1, 0, 1, max
    rt(HalValue::S64(i64::MIN));
    rt(HalValue::S64(-1));
    rt(HalValue::S64(0));
    rt(HalValue::S64(1));
    rt(HalValue::S64(i64::MAX));
}

#[test]
fn test_type_09_u64_roundtrip() {
    // S-TYPE-009: U64 序列化往返 — 0, 1, max
    rt(HalValue::U64(0));
    rt(HalValue::U64(1));
    rt(HalValue::U64(u64::MAX));
}

#[test]
fn test_type_10_f32_roundtrip() {
    // S-TYPE-010: F32 序列化往返 — use to_bits() for NaN safety
    rt_f32(HalValue::F32(0.0));
    rt_f32(HalValue::F32(-1.0));
    rt_f32(HalValue::F32(std::f32::consts::PI));
    rt_f32(HalValue::F32(f32::MIN));
    rt_f32(HalValue::F32(f32::MAX));
}

#[test]
fn test_type_11_f64_roundtrip() {
    // S-TYPE-011: F64 序列化往返 — use to_bits() for NaN safety
    rt_f64(HalValue::F64(0.0));
    rt_f64(HalValue::F64(-1.0));
    rt_f64(HalValue::F64(std::f64::consts::PI));
    rt_f64(HalValue::F64(f64::MIN));
    rt_f64(HalValue::F64(f64::MAX));
}

#[test]
fn test_type_12_blob_roundtrip() {
    // S-TYPE-012: Blob roundtrip — empty, small, 256-byte
    rt(HalValue::Blob(vec![]));
    rt(HalValue::Blob(vec![0, 1, 2]));
    rt(HalValue::Blob(vec![255; 256]));
}

#[test]
fn test_type_13_string_roundtrip() {
    // S-TYPE-013: String roundtrip
    rt(HalValue::String("".into()));
    rt(HalValue::String("hello".into()));
    rt(HalValue::String("中文".into()));
    // ponytail: max_len_string — 1KB ASCII
    let max_len = "a".repeat(1024);
    rt(HalValue::String(max_len));
}

#[test]
fn test_type_14_array_roundtrip() {
    // S-TYPE-014: Array<T> roundtrip — S32 elements
    // Arrange: 4-byte LE encoding of [0] as S32 = [0,0,0,0]
    let v = HalValue::Array { element_type: HalPinType::S32, data: vec![0, 0, 0, 0] };
    rt(v);
}

#[test]
fn test_type_15_blob_length_mismatch() {
    // S-TYPE-015: Blob length validation — corrupt length byte
    // Arrange: encode valid blob
    let v = HalValue::Blob(vec![1, 2, 3, 4]);
    let mut encoded = encode_halvalue(&v);
    // Corrupt the 4-byte length field (bytes 1-4 after type tag 0)
    let fake_len: u32 = 999;
    encoded[1..5].copy_from_slice(&fake_len.to_le_bytes());
    // Act
    let result = decode_halvalue(&encoded);
    // Assert
    assert!(
        matches!(result, Err(HalError::InvalidBlobLength { .. })),
        "expected InvalidBlobLength, got {:?}",
        result
    );
}

#[test]
fn test_type_16_array_type_mismatch() {
    // S-TYPE-016: Array element_type validation — corrupt element_type byte
    // Arrange: encode valid Array, then corrupt element_type tag (byte 1, after TAG_ARRAY)
    let v = HalValue::Array { element_type: HalPinType::S32, data: vec![0, 0, 0, 0] };
    let mut encoded = encode_halvalue(&v);
    encoded[1] = 0xFF; // invalid element_type tag
    // Act
    let result = decode_halvalue(&encoded);
    // Assert
    assert!(
        matches!(result, Err(HalError::TypeMismatch { .. })),
        "expected TypeMismatch, got {:?}",
        result
    );
}

#[test]
fn test_type_18_unknown_type_id() {
    // S-TYPE-018: Unknown type tag rejection — 0xFF
    // Arrange: manually construct buffer with type tag 0xFF
    let buf = [0xFF, 0x00];
    // Act
    let result = decode_halvalue(&buf);
    // Assert
    assert!(
        matches!(result, Err(HalError::UnknownHalType { type_id: 0xFF })),
        "expected UnknownHalType, got {:?}",
        result
    );
}

#[test]
fn test_type_19_nesting_limit() {
    // S-TYPE-019: Array of Blob — decode handles non-scalar element_type
    // Arrange: encode Array { element_type: Blob, data: single encoded empty blob }
    let inner_blob = encode_halvalue(&HalValue::Blob(vec![]));
    let v = HalValue::Array { element_type: HalPinType::Blob, data: inner_blob };
    // Act
    let encoded = encode_halvalue(&v);
    let decoded = decode_halvalue(&encoded).expect("decode Array<Blob> failed");
    // Assert
    match decoded {
        HalValue::Array { element_type, .. } => {
            assert_eq!(element_type, HalPinType::Blob);
        }
        _ => panic!("expected Array, got {:?}", decoded),
    }
}

#[test]
fn test_type_20_blob_empty() {
    // S-TYPE-020: Blob with declared length 0, actual 0 bytes
    rt(HalValue::Blob(vec![]));
}

#[test]
fn test_type_21_blob_max() {
    // S-TYPE-021: Blob with declared max size — 65535 bytes
    // ponytail: one large alloc, not production-size
    let data = vec![0u8; 65535];
    rt(HalValue::Blob(data));
}

#[test]
fn test_type_22_string_empty() {
    // S-TYPE-022: Empty string roundtrip
    rt(HalValue::String("".into()));
}

#[test]
fn test_type_23_string_unicode() {
    // S-TYPE-023: Unicode string roundtrip
    rt(HalValue::String("Hello 世界 🌍".into()));
}

#[test]
fn test_type_28_nan_bitwise() {
    // S-TYPE-028: NaN bitwise survival — encode f32::NAN, compare with to_bits()
    rt_f32(HalValue::F32(f32::NAN));
}

#[test]
fn test_type_30_pin_type_identity() {
    // S-TYPE-030: For each variant, pin_type() returns correct HalPinType
    assert_eq!(HalValue::Bool(true).pin_type(), HalPinType::Bool);
    assert_eq!(HalValue::Bool(false).pin_type(), HalPinType::Bool);
    assert_eq!(HalValue::S8(0).pin_type(), HalPinType::S8);
    assert_eq!(HalValue::U8(0).pin_type(), HalPinType::U8);
    assert_eq!(HalValue::S16(0).pin_type(), HalPinType::S16);
    assert_eq!(HalValue::U16(0).pin_type(), HalPinType::U16);
    assert_eq!(HalValue::S32(0).pin_type(), HalPinType::S32);
    assert_eq!(HalValue::U32(0).pin_type(), HalPinType::U32);
    assert_eq!(HalValue::S64(0).pin_type(), HalPinType::S64);
    assert_eq!(HalValue::U64(0).pin_type(), HalPinType::U64);
    assert_eq!(HalValue::F32(0.0).pin_type(), HalPinType::F32);
    assert_eq!(HalValue::F64(0.0).pin_type(), HalPinType::F64);
    assert_eq!(HalValue::Blob(vec![]).pin_type(), HalPinType::Blob);
    assert_eq!(HalValue::String("".into()).pin_type(), HalPinType::String);
    assert_eq!(
        HalValue::Array { element_type: HalPinType::S32, data: vec![] }.pin_type(),
        HalPinType::S32
    );
}

// ═══════════════════════════════════════════════════════════════
// P1 stubs — lower priority, implement in Phase 1 M0.5
// ═══════════════════════════════════════════════════════════════

#[test]
#[ignore = "P1 stub: lower priority, implement in Phase 1 M0.5"]
fn test_type_17_zero_value() {
    // S-TYPE-017: Zero-value encoding validation
    todo!("S-TYPE-017: Zero-value encoding");
}

#[test]
#[ignore = "P1 stub: lower priority, implement in Phase 1 M0.5"]
fn test_type_24_numeric_edges() {
    // S-TYPE-024: Numeric edge case roundtrip
    todo!("S-TYPE-024: Numeric edge case validation");
}

#[test]
#[ignore = "P1 stub: lower priority, implement in Phase 1 M0.5"]
fn test_type_25_container_large() {
    // S-TYPE-025: Large container stress
    todo!("S-TYPE-025: Large container boundary");
}

#[test]
#[ignore = "P1 stub: lower priority, implement in Phase 1 M0.5"]
fn test_type_26_type_mapping() {
    // S-TYPE-026: IEC type mapping verification
    todo!("S-TYPE-026: Type mapping coverage");
}

#[test]
#[ignore = "P1 stub: lower priority, implement in Phase 1 M0.5"]
fn test_type_27_stress_roundtrip() {
    // S-TYPE-027: Stress roundtrip across all types
    todo!("S-TYPE-027: Stress roundtrip");
}

#[test]
#[ignore = "P1 stub: lower priority, implement in Phase 1 M0.5"]
fn test_type_29_container_overlap() {
    // S-TYPE-029: Container encoding boundary verification
    todo!("S-TYPE-029: Container overlap");
}
