/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Compile IEC 61131-3 Function Block Diagram source into HalProgram JSON.
 *
 * Stub — FBD compiler → IL → HalProgram pipeline available in Phase 2a.
 */
export declare function compileFbd(source: string): string

/**
 * Compile G-code (RS274/NGC subset) source into a HalProgram JSON string.
 *
 * Stub — G-code compiler available; enable when CNC Phase 2 begins.
 */
export declare function compileGcode(source: string): string

/** Compile IEC 61131-3 Instruction List source into a HalProgram JSON string. */
export declare function compileIl(source: string): string

/**
 * Compile IEC 61131-3 Ladder Diagram source into a HalProgram JSON string.
 *
 * LD is compiled via IL: LD source → IL text → HalProgram.
 */
export declare function compileLd(source: string): string

/**
 * Compile IEC 61131-3 Sequential Function Chart source into HalProgram JSON.
 *
 * Stub — SFC compiler → IL → HalProgram pipeline available in Phase 2b.
 */
export declare function compileSfc(source: string): string

/**
 * Compile IEC 61131-3 Structured Text source into a HalProgram JSON string.
 *
 * Returns the serialized `HalProgram` on success, or a JSON diagnostic array
 * on compile error.
 */
export declare function compileSt(source: string): string

/**
 * Check whether the Controller process is alive.
 *
 * Attempts a UDS connection to the stored socket path.
 * Returns JSON: `{"alive": true, "pid": 12345, "uptime_sec": 120}`
 */
export declare function controllerHealth(): string

/**
 * Start the AUDESYS Controller as a child process.
 *
 * Spawns the binary at `binary_path`, then polls for the UDS socket at
 * `socket_path` to become available (100ms interval, 10s timeout).
 * Returns JSON: `{"pid": 12345, "socket": "/tmp/...", "status": "running"}`
 */
export declare function controllerStart(socketPath: string, binaryPath: string): string

/**
 * Stop the running Controller process.
 *
 * Sends SIGKILL to the child process and cleans up the UDS socket file.
 * Returns JSON: `{"status": "stopped"}`
 *
 * ponytail: SIGTERM-first graceful shutdown is not implemented — the
 * Controller is a local dev process, not a production server. Add SIGTERM
 * when the Controller has a signal handler for in-flight program save.
 */
export declare function controllerStop(): string

/** Set a breakpoint at the given instruction pointer. */
export declare function debugAddBreakpoint(ip: number): string

/** Connect to Controller for a persistent debug session. */
export declare function debugConnect(socketPath: string, secret: string): string

/** Disconnect the persistent debug session. */
export declare function debugDisconnect(): string

/** List all active breakpoints. */
export declare function debugGetBreakpoints(): string

/** Read VM register values (r0–r13) from the Controller. */
export declare function debugGetRegisters(): string

/** Get full debug state as a JSON string from the Controller. */
export declare function debugGetState(): string

/** Pause cycle execution on the Controller. */
export declare function debugPause(): string

/** Clear a breakpoint at the given instruction pointer. */
export declare function debugRemoveBreakpoint(ip: number): string

/** Resume cycle execution on the Controller. */
export declare function debugResume(): string

/** Single-step one cycle on the Controller. */
export declare function debugStep(): string

/**
 * Deploy HMI layout YAML to a running Controller via IPC method 0x17.
 *
 * Stub — DEPLOY_HMI_LAYOUT IPC available in Phase 1 follow-up.
 */
export declare function deployHmiLayout(socketPath: string, secret: string, yaml: string): string

/**
 * Deploy a compiled program (HalProgram JSON) to a running Controller.
 *
 * Merges the old `deploy_program` + `run_program` Tauri commands.
 * The program is loaded via IPC method 0x07 (LOAD_PROGRAM).
 */
export declare function deployProgram(socketPath: string, secret: string, programJson: string): string

/**
 * Query the Controller health status via UDS method 0x05 (HEALTH_QUERY).
 *
 * Merges the old `health_query` + `fetch_controller_metrics` Tauri commands.
 * Returns a health-report JSON string. Timeout: 2s.
 */
export declare function healthQuery(socketPath: string, secret: string): string

/**
 * Load a HAL configuration (YAML) to a running Controller via IPC.
 *
 * Stub — config manager module deferred.
 */
export declare function loadHalConfig(socketPath: string, secret: string, yaml: string): string

/** Load HMI layout YAML from a local file. */
export declare function loadHmiLayout(path: string): string

/** Open a project by reading its .audesys-project.yaml file. */
export declare function openProject(projectPath: string): string

/** Read a project source file. */
export declare function readProjectFile(filePath: string): string

/**
 * Read a signal value from a running Controller via one-shot UDS connection.
 *
 * Merges the old `read_controller_signal` + `controller_read_signal` Tauri
 * commands. Returns the HalValue as a JSON string.
 */
export declare function readSignal(socketPath: string, secret: string, signalName: string): string

/** Save HMI layout YAML to a local file. */
export declare function saveHmiLayout(path: string, yaml: string): string

/**
 * Snapshot all signals matching `pattern` from the Controller.
 *
 * Returns a JSON array of `{name, value}` objects.
 */
export declare function signalSnapshot(socketPath: string, secret: string, pattern: string): string

/** Create a new simulation environment. */
export declare function simCreate(cycleMs: number): string

/** Destroy the current simulation environment. */
export declare function simDestroy(): string

/** Step one simulation cycle. Returns signal states as JSON. */
export declare function simStep(): string
